<?php

/**
 * Implements hook_menu()
 *
 * Add menu option to Config - Services
 *
 * @return array
 */
function drupal_sugar_menu()
{
    $items = array();
    $items['admin/config/services/sugar'] = array(
        'title' => 'SugarCRM API Settings',
        'description' => t('Configure SugarCRM API settings'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('drupal_sugar_settings_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'drupal_sugar_settings_form.inc',
    );

    return $items;
}


/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Add the Sugar field name option to the form edit
 *
 * @todo Make this a dynamic dropdown from Sugar metadata
 * @todo save data!!
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function drupal_sugar_form_webform_component_edit_form_alter(&$form, &$form_state, $form_id)
{
    $form['sugar_field'] = array(
        '#type' => 'fieldset',
        //'#access' => user_access('administer comments'),
        '#title' => t('SugarCRM field'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        //'#group' => 'additional_settings',
        '#weight' => 100,
    );

    $form['sugar_field']['sugar'] = array(
        '#type' => 'textfield',
        '#title' => t('Field Name'),
        '#description' => t("Specifiy the SugarCRM field name.  You can find the field name in SugarCRM using Studio editor."),
        '#weight' => -1,
//        '#options' => array(
//            '' => '',
//            'Leads' => t('Leads'),
//            'Contacts' => t('Contacts'),
//        ),
//        '#default_value' => variable_get('sugar_module'),
    );
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * Add an option to select the Sugar module we wil post the data to
 *
 * @todo save data!!
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function drupal_sugar_form_webform_node_form_alter(&$form, &$form_state, $form_id)
{
//    /* Instantiate and authenticate */
//    $sugar = new \Spinegar\Sugar7Wrapper\Rest();
//
//    $sugar_url = variable_get('drupal_sugar_config_url');
//    // trim any trailing slash
//    $sugar_url = rtrim($sugar_url, '/');
//    $sugar_username = variable_get('drupal_sugar_config_username');
//    $sugar_password = variable_get('drupal_sugar_config_username');
//
//
//    $sugar->setUrl($sugar_url.'/rest/v10/')
//        ->setUsername($sugar_username)
//        ->setPassword($sugar_password)
//        ->connect();
//
//    /* Retrieve all records in the Accounts module */
//    $accounts = $sugar->search('Accounts');

    $form['sugar_module'] = array(
        '#type' => 'fieldset',
        //'#access' => user_access('administer comments'),
        '#title' => t('SugarCRM module'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#group' => 'additional_settings',
        '#weight' => 100,
    );

    $form['sugar_module']['sugar'] = array(
        '#type' => 'select',
        '#title' => t('Module'),
        '#description' => t("Specifiy the SugarCRM module this data is to be sent to"),
        '#options' => array(
            '' => '',
            'Leads' => t('Leads'),
            'Contacts' => t('Contacts'),
        ),
        '#default_value' => variable_get('sugar_module'),
    );
}

