<?php

/**
 *
 * @return mixed
 */
function drupal_sugar_admin() {
    $form = array();

    $form['drupal_sugar_config_url'] = array(
        '#type' => 'textfield',
        '#title' => t('SugarCRM URL'),
        '#default_value' => variable_get('drupal_sugar_config_url'),
        '#size' => 100,
        '#maxlength' => 255,
        //'#description' => t("SugarCRM URL."),
        '#required' => TRUE,
    );

    $form['drupal_sugar_config_username'] = array(
        '#type' => 'textfield',
        '#title' => t('SugarCRM API Username'),
        '#default_value' => variable_get('drupal_sugar_config_username'),
        '#size' => 30,
        '#maxlength' => 255,
        //'#description' => t("SugarCRM API Username."),
        '#required' => TRUE,
    );

    $form['drupal_sugar_config_password'] = array(
        '#type' => 'password',
        '#title' => t('SugarCRM API Password'),
        '#default_value' => variable_get('drupal_sugar_config_password'),
        '#size' => 30,
        '#maxlength' => 255,
        //'#description' => t("SugarCRM API Password."),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}


/**
 * Implements hook_menu()
 *
 * @return array
 */
function drupal_sugar_menu() {

    $items = array();

    $items['admin/settings/sugar'] = array(
        'title' => 'SugarCRM API Settings',
        'description' => 'Description of your On this date settings page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('drupal_sugar_admin'),
        'access arguments' => array('administer drupal_sugar settings'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}


/**
 * Implements hook_form_FORM_ID_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function drupal_sugar_form_contact_site_form_alter(&$form, &$form_state, $form_id) {
    // Add custom submit callback
    $form['#submit'][] = 'drupal_sugar_post_data';
    // Add hidden field for Sugar module - Leads
    $form['sugar_module'] = array(
        '#type' => 'hidden',
        '#default_value' => 'Leads',
    );
}


function drupal_sugar_post_data($form, &$form_state) {
    $var = 5;
}